"use client";

import React, { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import type { BusinessModuleSpec } from '@/lib/business-os';

type EmployeeStatus = 'active' | 'suspended' | 'deactive';
type Employee = { id: string; employeeCode?: string; name: string; title: string; department: string; email: string; status: string; role?: string; orgUnit?: string; skills?: string; branch?: string; managerName?: string; employmentType?: string; phone?: string; emergencyContact?: string; joiningDate?: string; probationEndDate?: string };
type Contract = { id: string; employeeId: string; employeeName: string; type: string; startDate: string; endDate: string | null; salaryStructure?: string; probationEndDate?: string };
type Attendance = { id: string; employeeId: string; employeeName: string; checkIn: string; checkOut: string | null; shiftLabel?: string };
type LeaveRow = { id: string; employeeId: string; employeeName: string; type: string; status: string; startDate: string; endDate: string };
type PayrollSlip = { id: string; employeeId: string; employeeName: string; netPay: number };
type PayrollRun = { id: string; periodStart: string; periodEnd: string; createdAt: string; approvalStatus: string; inputsSummary?: string; payslips: PayrollSlip[] };
type Candidate = { id: string; name: string; roleTitle: string; stage: string; source?: string; recruiter?: string; createdAt: string };
type OrganizationUnit = { id: string; name?: string; unitType?: string; parentName?: string; branch?: string; costCenter?: string; headcountPlan?: number };
type NamedRecord = { id: string; employeeId?: string; employeeName?: string; status?: string; [key: string]: unknown };
type HrApiErrorPayload = { ok?: boolean; error?: string; description?: string; code?: string; indexUrl?: string };
type HrPayload = { ok: boolean; employees?: Employee[]; organizationUnits?: OrganizationUnit[]; contracts?: Contract[]; attendance?: Attendance[]; shifts?: NamedRecord[]; attendanceCorrections?: NamedRecord[]; overtime?: NamedRecord[]; leaves?: LeaveRow[]; payrollRuns?: PayrollRun[]; candidates?: Candidate[]; requisitions?: NamedRecord[]; interviews?: NamedRecord[]; offers?: NamedRecord[]; onboarding?: NamedRecord[]; expenses?: NamedRecord[]; travel?: NamedRecord[]; performance?: NamedRecord[]; goals?: NamedRecord[]; learning?: NamedRecord[]; certifications?: NamedRecord[]; assets?: NamedRecord[]; documents?: NamedRecord[]; incidents?: NamedRecord[]; discipline?: NamedRecord[]; offboarding?: NamedRecord[] };

const CANDIDATE_FLOW = ['applied', 'screened', 'shortlisted', 'interview stage 1', 'interview stage 2', 'assessment', 'offer pending', 'hired', 'rejected', 'talent pool'];
const PEOPLE_PILLARS = ['Employee master and organization structure', 'Recruitment, onboarding, and lifecycle', 'Attendance, shifts, leave, payroll, and approvals', 'Claims, travel, learning, assets, compliance, incidents, and offboarding'];

async function parseApiPayload(response: Response): Promise<HrApiErrorPayload | null> { try { return (await response.json()) as HrApiErrorPayload; } catch { return null; } }
function formatApiError(payload: HrApiErrorPayload | null, fallback: string): string { if (!payload) return fallback; const parts = [payload.error, payload.description, payload.code].filter(Boolean); return parts.length > 0 ? parts.join(' | ') : fallback; }
function asDate(value?: string | null) { if (!value) return 'n/a'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleDateString(); }
function asDateTime(value?: string | null) { if (!value) return 'n/a'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString(); }

export function HrOperationsContent({ module }: { module: BusinessModuleSpec }) {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [organizationUnits, setOrganizationUnits] = useState<OrganizationUnit[]>([]);
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [attendance, setAttendance] = useState<Attendance[]>([]);
  const [shifts, setShifts] = useState<NamedRecord[]>([]);
  const [attendanceCorrections, setAttendanceCorrections] = useState<NamedRecord[]>([]);
  const [overtime, setOvertime] = useState<NamedRecord[]>([]);
  const [leaves, setLeaves] = useState<LeaveRow[]>([]);
  const [payrollRuns, setPayrollRuns] = useState<PayrollRun[]>([]);
  const [candidates, setCandidates] = useState<Candidate[]>([]);
  const [requisitions, setRequisitions] = useState<NamedRecord[]>([]);
  const [interviews, setInterviews] = useState<NamedRecord[]>([]);
  const [offers, setOffers] = useState<NamedRecord[]>([]);
  const [onboarding, setOnboarding] = useState<NamedRecord[]>([]);
  const [expenses, setExpenses] = useState<NamedRecord[]>([]);
  const [travel, setTravel] = useState<NamedRecord[]>([]);
  const [performance, setPerformance] = useState<NamedRecord[]>([]);
  const [goals, setGoals] = useState<NamedRecord[]>([]);
  const [learning, setLearning] = useState<NamedRecord[]>([]);
  const [certifications, setCertifications] = useState<NamedRecord[]>([]);
  const [assets, setAssets] = useState<NamedRecord[]>([]);
  const [documents, setDocuments] = useState<NamedRecord[]>([]);
  const [incidents, setIncidents] = useState<NamedRecord[]>([]);
  const [discipline, setDiscipline] = useState<NamedRecord[]>([]);
  const [offboarding, setOffboarding] = useState<NamedRecord[]>([]);
  const [apiError, setApiError] = useState<string | null>(null);
  const [apiErrorLink, setApiErrorLink] = useState<string | null>(null);

  const [employeeName, setEmployeeName] = useState(''); const [employeeTitle, setEmployeeTitle] = useState(''); const [employeeDepartment, setEmployeeDepartment] = useState(''); const [employeeEmail, setEmployeeEmail] = useState(''); const [employeeRole, setEmployeeRole] = useState(''); const [employeeOrgUnit, setEmployeeOrgUnit] = useState(''); const [employeeSkills, setEmployeeSkills] = useState(''); const [employeeBranch, setEmployeeBranch] = useState(''); const [employeeManager, setEmployeeManager] = useState(''); const [employmentType, setEmploymentType] = useState('full-time'); const [employeePhone, setEmployeePhone] = useState(''); const [emergencyContact, setEmergencyContact] = useState(''); const [joiningDate, setJoiningDate] = useState(''); const [probationEndDate, setProbationEndDate] = useState('');
  const [orgName, setOrgName] = useState(''); const [orgUnitType, setOrgUnitType] = useState('department'); const [orgParentName, setOrgParentName] = useState(''); const [orgBranch, setOrgBranch] = useState(''); const [orgCostCenter, setOrgCostCenter] = useState(''); const [orgHeadcountPlan, setOrgHeadcountPlan] = useState('0');
  const [contractEmployeeId, setContractEmployeeId] = useState(''); const [contractType, setContractType] = useState('full-time'); const [contractStart, setContractStart] = useState(''); const [contractEnd, setContractEnd] = useState(''); const [salaryStructure, setSalaryStructure] = useState('');
  const [attendanceEmployeeId, setAttendanceEmployeeId] = useState(''); const [shiftLabel, setShiftLabel] = useState('day'); const [shiftDate, setShiftDate] = useState(''); const [shiftStartTime, setShiftStartTime] = useState(''); const [shiftEndTime, setShiftEndTime] = useState('');
  const [leaveEmployeeId, setLeaveEmployeeId] = useState(''); const [leaveType, setLeaveType] = useState('annual'); const [leaveStart, setLeaveStart] = useState(''); const [leaveEnd, setLeaveEnd] = useState('');
  const [payrollEmployeeId, setPayrollEmployeeId] = useState(''); const [periodStart, setPeriodStart] = useState(''); const [periodEnd, setPeriodEnd] = useState(''); const [netPay, setNetPay] = useState('0'); const [payrollInputsSummary, setPayrollInputsSummary] = useState('');
  const [candidateName, setCandidateName] = useState(''); const [candidateRoleTitle, setCandidateRoleTitle] = useState(''); const [candidateStage, setCandidateStage] = useState('applied'); const [candidateSource, setCandidateSource] = useState(''); const [candidateRecruiter, setCandidateRecruiter] = useState('');
  const [correctionEmployeeId, setCorrectionEmployeeId] = useState(''); const [correctionReason, setCorrectionReason] = useState(''); const [correctionCheckIn, setCorrectionCheckIn] = useState(''); const [correctionCheckOut, setCorrectionCheckOut] = useState('');
  const [overtimeEmployeeId, setOvertimeEmployeeId] = useState(''); const [overtimeDate, setOvertimeDate] = useState(''); const [overtimeHours, setOvertimeHours] = useState('0'); const [overtimePolicy, setOvertimePolicy] = useState('');
  const [requisitionTitle, setRequisitionTitle] = useState(''); const [requisitionDepartment, setRequisitionDepartment] = useState(''); const [requisitionBranch, setRequisitionBranch] = useState(''); const [requisitionOpenings, setRequisitionOpenings] = useState('1');
  const [interviewCandidateId, setInterviewCandidateId] = useState(''); const [interviewCandidateName, setInterviewCandidateName] = useState(''); const [interviewStage, setInterviewStage] = useState('screening'); const [interviewAt, setInterviewAt] = useState(''); const [interviewerName, setInterviewerName] = useState('');
  const [offerCandidateId, setOfferCandidateId] = useState(''); const [offerCandidateName, setOfferCandidateName] = useState(''); const [offerRoleTitle, setOfferRoleTitle] = useState(''); const [offerSalary, setOfferSalary] = useState('0');
  const [goalEmployeeId, setGoalEmployeeId] = useState(''); const [goalTitle, setGoalTitle] = useState(''); const [goalDueDate, setGoalDueDate] = useState(''); const [goalAlignment, setGoalAlignment] = useState('');
  const [certEmployeeId, setCertEmployeeId] = useState(''); const [certName, setCertName] = useState(''); const [certIssuer, setCertIssuer] = useState(''); const [certExpiry, setCertExpiry] = useState('');
  const [genericEmployeeId, setGenericEmployeeId] = useState(''); const [genericA, setGenericA] = useState(''); const [genericB, setGenericB] = useState(''); const [genericC, setGenericC] = useState(''); const [genericD, setGenericD] = useState('');

  const load = async () => {
    setApiError(null); setApiErrorLink(null);
    try {
      const response = await fetch('/api/business/hr/operations', { cache: 'no-store' });
      const parsedPayload = await parseApiPayload(response);
      if (!response.ok || parsedPayload?.ok === false) { if (parsedPayload?.indexUrl) setApiErrorLink(parsedPayload.indexUrl); throw new Error(formatApiError(parsedPayload, 'Failed to load HR operations data.')); }
      const data = parsedPayload as HrPayload;
      setEmployees(data.employees ?? []); setOrganizationUnits(data.organizationUnits ?? []); setContracts(data.contracts ?? []); setAttendance(data.attendance ?? []); setShifts(data.shifts ?? []); setAttendanceCorrections(data.attendanceCorrections ?? []); setOvertime(data.overtime ?? []); setLeaves(data.leaves ?? []); setPayrollRuns(data.payrollRuns ?? []); setCandidates(data.candidates ?? []); setRequisitions(data.requisitions ?? []); setInterviews(data.interviews ?? []); setOffers(data.offers ?? []); setOnboarding(data.onboarding ?? []); setExpenses(data.expenses ?? []); setTravel(data.travel ?? []); setPerformance(data.performance ?? []); setGoals(data.goals ?? []); setLearning(data.learning ?? []); setCertifications(data.certifications ?? []); setAssets(data.assets ?? []); setDocuments(data.documents ?? []); setIncidents(data.incidents ?? []); setDiscipline(data.discipline ?? []); setOffboarding(data.offboarding ?? []);
    } catch (error) {
      setApiError(error instanceof Error ? error.message : 'Failed to load HR operations data.');
      setEmployees((module.records ?? []).map((record, index) => ({ id: `seed-emp-${index}`, name: record.title, title: record.subtitle, department: 'General', email: `employee${index + 1}@airtyn.local`, status: 'active' })));
    }
  };

  useEffect(() => { void load(); }, [module.records]);
  const employeeOptions = useMemo(() => employees.map((employee) => ({ label: `${employee.name} (${employee.employeeCode ?? employee.id.slice(-4)})`, value: employee.id })), [employees]);
  const requestedLeaves = useMemo(() => leaves.filter((item) => item.status === 'requested'), [leaves]);
  const pendingPayroll = useMemo(() => payrollRuns.filter((item) => item.approvalStatus === 'pending_approval'), [payrollRuns]);
  const pendingOnboarding = useMemo(() => onboarding.filter((item) => item.status !== 'completed'), [onboarding]);
  const pendingClaims = useMemo(() => expenses.filter((item) => item.status === 'submitted'), [expenses]);
  const pendingTravel = useMemo(() => travel.filter((item) => item.status === 'submitted'), [travel]);
  const openOffboarding = useMemo(() => offboarding.filter((item) => item.status !== 'completed'), [offboarding]);
  const pendingCorrections = useMemo(() => attendanceCorrections.filter((item) => String(item.status ?? '') === 'requested'), [attendanceCorrections]);
  const pendingOvertime = useMemo(() => overtime.filter((item) => String(item.status ?? '') === 'pending_approval'), [overtime]);
  const activeOffers = useMemo(() => offers.filter((item) => String(item.status ?? '') !== 'accepted'), [offers]);
  const currentEmployee = employees[0];
  const absenteeismRate = employees.length === 0 ? 0 : Math.round((requestedLeaves.length / employees.length) * 100);
  const overtimeHoursTotal = overtime.reduce((sum, row) => sum + Number(row.hours ?? 0), 0);
  const trainingCompletionRate = learning.length === 0 ? 0 : Math.round((learning.filter((item) => String(item.status ?? '') === 'completed').length / learning.length) * 100);

  const submitEntity = async (body: Record<string, unknown>, fallback: string) => { setApiError(null); setApiErrorLink(null); const response = await fetch('/api/business/hr/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await parseApiPayload(response); if (!response.ok || payload?.ok === false) { if (payload?.indexUrl) setApiErrorLink(payload.indexUrl); throw new Error(formatApiError(payload, fallback)); } await load(); };
  const patchEntity = async (body: Record<string, unknown>, fallback: string) => { setApiError(null); setApiErrorLink(null); const response = await fetch('/api/business/hr/operations', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await parseApiPayload(response); if (!response.ok || payload?.ok === false) { if (payload?.indexUrl) setApiErrorLink(payload.indexUrl); throw new Error(formatApiError(payload, fallback)); } await load(); };

  const addEmployee = async () => { if (!employeeName.trim() || !employeeTitle.trim() || !employeeEmail.trim()) return; try { await submitEntity({ entityType: 'employee', name: employeeName.trim(), email: employeeEmail.trim().toLowerCase(), title: employeeTitle.trim(), department: employeeDepartment.trim() || 'General', role: employeeRole.trim() || undefined, orgUnit: employeeOrgUnit.trim() || undefined, skills: employeeSkills.trim() || undefined, branch: employeeBranch.trim() || undefined, managerName: employeeManager.trim() || undefined, employmentType, phone: employeePhone.trim() || undefined, emergencyContact: emergencyContact.trim() || undefined, joiningDate: joiningDate ? new Date(joiningDate).toISOString() : undefined, probationEndDate: probationEndDate ? new Date(probationEndDate).toISOString() : undefined }, 'Failed to add employee.'); setEmployeeName(''); setEmployeeTitle(''); setEmployeeDepartment(''); setEmployeeEmail(''); setEmployeeRole(''); setEmployeeOrgUnit(''); setEmployeeSkills(''); setEmployeeBranch(''); setEmployeeManager(''); setEmploymentType('full-time'); setEmployeePhone(''); setEmergencyContact(''); setJoiningDate(''); setProbationEndDate(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to add employee.'); } };
  const addOrganizationUnit = async () => { if (!orgName.trim()) return; try { await submitEntity({ entityType: 'organization', name: orgName.trim(), unitType: orgUnitType, parentName: orgParentName.trim() || undefined, branch: orgBranch.trim() || undefined, costCenter: orgCostCenter.trim() || undefined, headcountPlan: Number(orgHeadcountPlan || 0) }, 'Failed to add organization unit.'); setOrgName(''); setOrgParentName(''); setOrgBranch(''); setOrgCostCenter(''); setOrgHeadcountPlan('0'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to add organization unit.'); } };
  const addContract = async () => { if (!contractEmployeeId || !contractStart) return; try { await submitEntity({ entityType: 'contract', employeeId: contractEmployeeId, contractType, startDate: new Date(contractStart).toISOString(), endDate: contractEnd ? new Date(contractEnd).toISOString() : undefined, salaryStructure: salaryStructure.trim() || undefined, probationEndDate: probationEndDate ? new Date(probationEndDate).toISOString() : undefined }, 'Failed to add contract.'); setContractType('full-time'); setContractStart(''); setContractEnd(''); setSalaryStructure(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to add contract.'); } };
  const clockIn = async () => { if (!attendanceEmployeeId) return; try { await submitEntity({ entityType: 'attendance', employeeId: attendanceEmployeeId, checkIn: new Date().toISOString(), shiftLabel }, 'Failed to log attendance.'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to log attendance.'); } };
  const createShift = async () => { if (!attendanceEmployeeId || !shiftDate) return; try { await submitEntity({ entityType: 'shift', employeeId: attendanceEmployeeId, shiftLabel, shiftDate: new Date(shiftDate).toISOString(), branch: employeeBranch.trim() || undefined, startTime: shiftStartTime || undefined, endTime: shiftEndTime || undefined }, 'Failed to create shift.'); setShiftDate(''); setShiftStartTime(''); setShiftEndTime(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create shift.'); } };
  const requestLeave = async () => { if (!leaveEmployeeId || !leaveStart || !leaveEnd) return; try { await submitEntity({ entityType: 'leave', employeeId: leaveEmployeeId, leaveType, startDate: new Date(leaveStart).toISOString(), endDate: new Date(leaveEnd).toISOString() }, 'Failed to request leave.'); setLeaveStart(''); setLeaveEnd(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to request leave.'); } };
  const createPayrollRun = async () => { const parsedNetPay = Number(netPay); if (!payrollEmployeeId || !periodStart || !periodEnd || Number.isNaN(parsedNetPay) || parsedNetPay < 0) return; try { await submitEntity({ entityType: 'payroll', employeeId: payrollEmployeeId, periodStart: new Date(periodStart).toISOString(), periodEnd: new Date(periodEnd).toISOString(), netPay: parsedNetPay, inputsSummary: payrollInputsSummary.trim() || undefined }, 'Failed to create payroll run.'); setPeriodStart(''); setPeriodEnd(''); setNetPay('0'); setPayrollInputsSummary(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create payroll run.'); } };
  const addCandidate = async () => { if (!candidateName.trim() || !candidateRoleTitle.trim()) return; try { await submitEntity({ entityType: 'candidate', name: candidateName.trim(), roleTitle: candidateRoleTitle.trim(), stage: candidateStage, source: candidateSource.trim() || undefined, recruiter: candidateRecruiter.trim() || undefined }, 'Failed to add candidate.'); setCandidateName(''); setCandidateRoleTitle(''); setCandidateStage('applied'); setCandidateSource(''); setCandidateRecruiter(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to add candidate.'); } };
  const createAttendanceCorrection = async () => { if (!correctionEmployeeId || !correctionReason.trim()) return; try { await submitEntity({ entityType: 'attendance_correction', employeeId: correctionEmployeeId, requestedCheckIn: correctionCheckIn ? new Date(correctionCheckIn).toISOString() : undefined, requestedCheckOut: correctionCheckOut ? new Date(correctionCheckOut).toISOString() : undefined, reason: correctionReason.trim() }, 'Failed to create attendance correction.'); setCorrectionReason(''); setCorrectionCheckIn(''); setCorrectionCheckOut(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create attendance correction.'); } };
  const createOvertimeRecord = async () => { const hours = Number(overtimeHours); if (!overtimeEmployeeId || !overtimeDate || Number.isNaN(hours) || hours < 0) return; try { await submitEntity({ entityType: 'overtime', employeeId: overtimeEmployeeId, workDate: new Date(overtimeDate).toISOString(), hours, policyName: overtimePolicy.trim() || undefined }, 'Failed to create overtime record.'); setOvertimeDate(''); setOvertimeHours('0'); setOvertimePolicy(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create overtime record.'); } };
  const createRequisition = async () => { const openings = Number(requisitionOpenings); if (!requisitionTitle.trim() || !requisitionDepartment.trim() || Number.isNaN(openings) || openings <= 0) return; try { await submitEntity({ entityType: 'requisition', title: requisitionTitle.trim(), department: requisitionDepartment.trim(), branch: requisitionBranch.trim() || undefined, openings }, 'Failed to create requisition.'); setRequisitionTitle(''); setRequisitionDepartment(''); setRequisitionBranch(''); setRequisitionOpenings('1'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create requisition.'); } };
  const createInterview = async () => { if (!interviewCandidateId || !interviewCandidateName.trim() || !interviewAt) return; try { await submitEntity({ entityType: 'interview', candidateId: interviewCandidateId, candidateName: interviewCandidateName.trim(), stage: interviewStage, scheduledAt: new Date(interviewAt).toISOString(), interviewer: interviewerName.trim() || undefined }, 'Failed to schedule interview.'); setInterviewCandidateId(''); setInterviewCandidateName(''); setInterviewStage('screening'); setInterviewAt(''); setInterviewerName(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to schedule interview.'); } };
  const createOffer = async () => { const proposedSalary = Number(offerSalary); if (!offerCandidateId || !offerCandidateName.trim() || !offerRoleTitle.trim()) return; try { await submitEntity({ entityType: 'offer', candidateId: offerCandidateId, candidateName: offerCandidateName.trim(), roleTitle: offerRoleTitle.trim(), proposedSalary: Number.isNaN(proposedSalary) ? undefined : proposedSalary }, 'Failed to create offer.'); setOfferCandidateId(''); setOfferCandidateName(''); setOfferRoleTitle(''); setOfferSalary('0'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create offer.'); } };
  const createOnboarding = async () => { if (!genericEmployeeId || !genericA.trim()) return; try { await submitEntity({ entityType: 'onboarding', employeeId: genericEmployeeId, templateName: genericA.trim(), buddyName: genericB.trim() || undefined, firstWeekPlan: genericC.trim() || undefined, status: genericD.trim() || 'planned' }, 'Failed to create onboarding plan.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create onboarding plan.'); } };
  const addExpense = async () => { const amount = Number(genericB || 0); if (!genericEmployeeId || !genericA.trim() || Number.isNaN(amount) || amount <= 0) return; try { await submitEntity({ entityType: 'expense', employeeId: genericEmployeeId, category: genericA.trim(), amount, description: genericC.trim() || undefined }, 'Failed to submit expense claim.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to submit expense claim.'); } };
  const addTravel = async () => { if (!genericEmployeeId || !genericA.trim() || !genericB || !genericC) return; try { await submitEntity({ entityType: 'travel', employeeId: genericEmployeeId, destination: genericA.trim(), purpose: genericD.trim() || 'Business travel', startDate: new Date(genericB).toISOString(), endDate: new Date(genericC).toISOString() }, 'Failed to create travel request.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create travel request.'); } };
  const addPerformanceReview = async () => { if (!genericEmployeeId || !genericA.trim() || !genericB.trim()) return; try { await submitEntity({ entityType: 'performance', employeeId: genericEmployeeId, cycleName: genericA.trim(), rating: genericB.trim(), managerName: genericC.trim() || undefined, goalsSummary: genericD.trim() || undefined }, 'Failed to create performance review.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create performance review.'); } };
  const createGoal = async () => { if (!goalEmployeeId || !goalTitle.trim()) return; try { await submitEntity({ entityType: 'goal', employeeId: goalEmployeeId, title: goalTitle.trim(), dueDate: goalDueDate ? new Date(goalDueDate).toISOString() : undefined, alignment: goalAlignment.trim() || undefined }, 'Failed to create goal.'); setGoalTitle(''); setGoalDueDate(''); setGoalAlignment(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create goal.'); } };
  const addLearningPlan = async () => { if (!genericEmployeeId || !genericA.trim()) return; try { await submitEntity({ entityType: 'learning', employeeId: genericEmployeeId, courseName: genericA.trim(), provider: genericB.trim() || undefined, dueDate: genericC ? new Date(genericC).toISOString() : undefined, status: genericD.trim() || 'assigned' }, 'Failed to assign learning plan.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to assign learning plan.'); } };
  const createCertification = async () => { if (!certEmployeeId || !certName.trim()) return; try { await submitEntity({ entityType: 'certification', employeeId: certEmployeeId, certificationName: certName.trim(), issuer: certIssuer.trim() || undefined, expiryDate: certExpiry ? new Date(certExpiry).toISOString() : undefined }, 'Failed to create certification.'); setCertName(''); setCertIssuer(''); setCertExpiry(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to create certification.'); } };
  const assignAsset = async () => { if (!genericEmployeeId || !genericA.trim()) return; try { await submitEntity({ entityType: 'asset', employeeId: genericEmployeeId, assetName: genericA.trim(), assetTag: genericB.trim() || undefined, assignedAt: genericC ? new Date(genericC).toISOString() : undefined, status: genericD.trim() || 'assigned' }, 'Failed to assign asset.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to assign asset.'); } };
  const addDocument = async () => { if (!genericEmployeeId || !genericA.trim()) return; try { await submitEntity({ entityType: 'document', employeeId: genericEmployeeId, documentName: [genericA.trim(), genericB.trim()].filter(Boolean).join(' - '), expiryDate: genericC ? new Date(genericC).toISOString() : undefined, status: genericD.trim() || 'valid' }, 'Failed to add compliance document.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to add compliance document.'); } };
  const addIncident = async () => { if (!genericEmployeeId || !genericA.trim() || !genericC) return; try { await submitEntity({ entityType: 'incident', employeeId: genericEmployeeId, incidentType: genericA.trim(), severity: genericB.trim() || 'medium', occurredAt: new Date(genericC).toISOString(), notes: genericD.trim() || undefined }, 'Failed to log incident.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to log incident.'); } };
  const addDisciplineCase = async () => { if (!genericEmployeeId || !genericA.trim()) return; try { await submitEntity({ entityType: 'discipline', employeeId: genericEmployeeId, caseType: genericA.trim(), status: genericB.trim() || 'open', notes: [genericC.trim(), genericD.trim()].filter(Boolean).join(' | ') || undefined }, 'Failed to log discipline case.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to log discipline case.'); } };
  const startOffboarding = async () => { if (!genericEmployeeId || !genericA.trim() || !genericB) return; try { await submitEntity({ entityType: 'offboarding', employeeId: genericEmployeeId, reason: genericA.trim(), lastWorkingDate: new Date(genericB).toISOString(), status: genericD.trim() || 'planned' }, 'Failed to start offboarding.'); setGenericA(''); setGenericB(''); setGenericC(''); setGenericD(''); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to start offboarding.'); } };

  const updateLeaveStatus = async (recordId: string, status: string) => { try { await patchEntity({ entityType: 'leave', id: recordId, status }, 'Failed to update leave request.'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to update leave request.'); } };
  const updateEmployeeStatus = async (recordId: string, status: EmployeeStatus) => { try { await patchEntity({ entityType: 'employee', id: recordId, status }, 'Failed to update employee status.'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to update employee status.'); } };
  const advanceCandidate = async (recordId: string, currentStage: string) => { const index = CANDIDATE_FLOW.indexOf(currentStage); const nextStage = index >= 0 && index < CANDIDATE_FLOW.length - 1 ? CANDIDATE_FLOW[index + 1] : currentStage; try { await patchEntity({ entityType: 'candidate', id: recordId, stage: nextStage }, 'Failed to move candidate.'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to move candidate.'); } };
  const reviewPayroll = async (recordId: string, approval: 'approved' | 'rejected') => { try { await patchEntity({ entityType: 'payroll', id: recordId, approval }, 'Failed to review payroll run.'); } catch (error) { setApiError(error instanceof Error ? error.message : 'Failed to review payroll run.'); } };
  const updateRecordStatus = async (entityType: string, recordId: string, status: string) => { try { await patchEntity({ entityType, id: recordId, status }, `Failed to update ${entityType} record.`); } catch (error) { setApiError(error instanceof Error ? error.message : `Failed to update ${entityType} record.`); } };

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-4">
        <Card><CardHeader><CardTitle>People Ops OS</CardTitle><CardDescription>Connected HR lifecycle for operations, compliance, and growth.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-600">{PEOPLE_PILLARS.map((pillar) => <div key={pillar} className="rounded-lg border border-dashed border-slate-200 px-3 py-2">{pillar}</div>)}</CardContent></Card>
        <Card><CardHeader><CardTitle>Headcount</CardTitle><CardDescription>Employees and onboarding pipeline.</CardDescription></CardHeader><CardContent className="space-y-2"><div className="text-3xl font-semibold text-slate-900">{employees.length}</div><div className="text-sm text-slate-500">{onboarding.length} onboarding cases</div></CardContent></Card>
        <Card><CardHeader><CardTitle>Workforce control</CardTitle><CardDescription>Attendance, shifts, and leave.</CardDescription></CardHeader><CardContent className="space-y-2"><div className="text-3xl font-semibold text-slate-900">{attendance.length}</div><div className="text-sm text-slate-500">{shifts.length} shifts, {requestedLeaves.length} leave approvals</div></CardContent></Card>
        <Card><CardHeader><CardTitle>Compliance queue</CardTitle><CardDescription>Claims, travel, incidents, offboarding.</CardDescription></CardHeader><CardContent className="space-y-2"><div className="text-3xl font-semibold text-slate-900">{pendingClaims.length + pendingTravel.length + openOffboarding.length}</div><div className="text-sm text-slate-500">{documents.length} docs, {incidents.length} incidents, {discipline.length} cases</div></CardContent></Card>
      </div>

      {apiError ? <Card className="border-rose-200 bg-rose-50"><CardHeader><CardTitle>HR data needs attention</CardTitle><CardDescription>{apiError}</CardDescription></CardHeader><CardContent>{apiErrorLink ? <a className="text-sm underline" href={apiErrorLink} target="_blank" rel="noreferrer">Open Firestore index instructions</a> : null}</CardContent></Card> : null}

      <datalist id="hr-employee-options">{employeeOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</datalist>

      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList className="h-auto w-full justify-start gap-2 overflow-x-auto rounded-xl border bg-white p-2">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="people">People</TabsTrigger>
          <TabsTrigger value="recruitment">Recruitment</TabsTrigger>
          <TabsTrigger value="workforce">Workforce</TabsTrigger>
          <TabsTrigger value="payroll">Payroll</TabsTrigger>
          <TabsTrigger value="operations">Operations</TabsTrigger>
          <TabsTrigger value="self-service">Self Service</TabsTrigger>
          <TabsTrigger value="manager">Manager</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
          <TabsTrigger value="workflow">Workflow</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          <div className="grid gap-4 lg:grid-cols-3">
            <Card className="lg:col-span-2"><CardHeader><CardTitle>HR architecture</CardTitle><CardDescription>{module.summary}</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 text-sm text-slate-600">{module.features.map((feature) => <div key={feature} className="rounded-xl border bg-slate-50 p-3">{feature}</div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Core records</CardTitle><CardDescription>HR entities active in the workspace.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-600">{module.coreObjects.map((item) => <div key={item} className="flex items-center justify-between rounded-lg border px-3 py-2"><span>{item}</span><Badge variant="secondary">Live</Badge></div>)}</CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-5">
            <Card><CardHeader><CardTitle>Leave approvals</CardTitle></CardHeader><CardContent className="space-y-3">{requestedLeaves.length === 0 ? <div className="text-sm text-slate-500">No pending leave requests.</div> : requestedLeaves.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{item.employeeName}</div><div className="text-slate-500">{item.type} | {asDate(item.startDate)} to {asDate(item.endDate)}</div><div className="mt-2 flex gap-2"><Button size="sm" onClick={() => void updateLeaveStatus(item.id, 'approved')}>Approve</Button><Button size="sm" variant="outline" onClick={() => void updateLeaveStatus(item.id, 'rejected')}>Reject</Button></div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Payroll approvals</CardTitle></CardHeader><CardContent className="space-y-3">{pendingPayroll.length === 0 ? <div className="text-sm text-slate-500">No payroll runs waiting.</div> : pendingPayroll.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{asDate(item.periodStart)} to {asDate(item.periodEnd)}</div><div className="text-slate-500">{item.payslips.length} payslips</div><div className="mt-2 flex gap-2"><Button size="sm" onClick={() => void reviewPayroll(item.id, 'approved')}>Approve</Button><Button size="sm" variant="outline" onClick={() => void reviewPayroll(item.id, 'rejected')}>Reject</Button></div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Onboarding queue</CardTitle></CardHeader><CardContent className="space-y-3">{pendingOnboarding.length === 0 ? <div className="text-sm text-slate-500">All onboarding completed.</div> : pendingOnboarding.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(item.templateName ?? 'Template')} | {String(item.status ?? 'scheduled')}</div><Button size="sm" className="mt-2" onClick={() => void updateRecordStatus('onboarding', item.id, 'completed')}>Mark complete</Button></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Claims and travel</CardTitle></CardHeader><CardContent className="space-y-3">{pendingClaims.concat(pendingTravel).length === 0 ? <div className="text-sm text-slate-500">No approvals waiting.</div> : pendingClaims.concat(pendingTravel).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(item.category ?? item.destination ?? 'Request')} | {String(item.status ?? 'submitted')}</div><Button size="sm" className="mt-2" onClick={() => void updateRecordStatus(item.destination ? 'travel' : 'expense', item.id, 'approved')}>Approve</Button></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Offboarding queue</CardTitle></CardHeader><CardContent className="space-y-3">{openOffboarding.length === 0 ? <div className="text-sm text-slate-500">No active separation cases.</div> : openOffboarding.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(item.reason ?? 'Separation')} | {String(item.status ?? 'initiated')}</div><Button size="sm" className="mt-2" onClick={() => void updateRecordStatus('offboarding', item.id, 'completed')}>Complete</Button></div>)}</CardContent></Card>
          </div>
        </TabsContent>

        <TabsContent value="people" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Employee master</CardTitle><CardDescription>Create employee records with lifecycle details.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Employee name" value={employeeName} onChange={(event) => setEmployeeName(event.target.value)} /><Input placeholder="Job title" value={employeeTitle} onChange={(event) => setEmployeeTitle(event.target.value)} /><Input placeholder="Department" value={employeeDepartment} onChange={(event) => setEmployeeDepartment(event.target.value)} /><Input placeholder="Work email" value={employeeEmail} onChange={(event) => setEmployeeEmail(event.target.value)} /><Input placeholder="Role" value={employeeRole} onChange={(event) => setEmployeeRole(event.target.value)} /><Input placeholder="Org unit" value={employeeOrgUnit} onChange={(event) => setEmployeeOrgUnit(event.target.value)} /><Input placeholder="Branch / location" value={employeeBranch} onChange={(event) => setEmployeeBranch(event.target.value)} /><Input placeholder="Manager name" value={employeeManager} onChange={(event) => setEmployeeManager(event.target.value)} /><Input placeholder="Employment type" value={employmentType} onChange={(event) => setEmploymentType(event.target.value)} /><Input placeholder="Phone" value={employeePhone} onChange={(event) => setEmployeePhone(event.target.value)} /><Input placeholder="Emergency contact" value={emergencyContact} onChange={(event) => setEmergencyContact(event.target.value)} /><Input placeholder="Skills / tags" value={employeeSkills} onChange={(event) => setEmployeeSkills(event.target.value)} /><Input type="date" value={joiningDate} onChange={(event) => setJoiningDate(event.target.value)} /><Input type="date" value={probationEndDate} onChange={(event) => setProbationEndDate(event.target.value)} /><div className="md:col-span-2"><Button onClick={() => void addEmployee()}>Add employee</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Organization structure</CardTitle><CardDescription>Branches, departments, teams, and cost centers.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Unit name" value={orgName} onChange={(event) => setOrgName(event.target.value)} /><Input placeholder="Unit type" value={orgUnitType} onChange={(event) => setOrgUnitType(event.target.value)} /><Input placeholder="Parent unit" value={orgParentName} onChange={(event) => setOrgParentName(event.target.value)} /><Input placeholder="Branch" value={orgBranch} onChange={(event) => setOrgBranch(event.target.value)} /><Input placeholder="Cost center" value={orgCostCenter} onChange={(event) => setOrgCostCenter(event.target.value)} /><Input placeholder="Headcount plan" value={orgHeadcountPlan} onChange={(event) => setOrgHeadcountPlan(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void addOrganizationUnit()}>Add organization unit</Button></div></CardContent></Card>
          </div>
          <Card><CardHeader><CardTitle>Employee directory</CardTitle><CardDescription>Live employee master with lifecycle controls and context.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-slate-500"><tr><th className="pb-3">Employee</th><th className="pb-3">Org</th><th className="pb-3">Employment</th><th className="pb-3">Manager</th><th className="pb-3">Contacts</th><th className="pb-3">Joined</th><th className="pb-3">Status</th></tr></thead><tbody className="divide-y">{employees.map((employee) => <tr key={employee.id}><td className="py-3"><div className="font-medium">{employee.name}</div><div className="text-slate-500">{employee.title}</div><div className="text-xs text-slate-400">{employee.employeeCode ?? employee.id}</div></td><td className="py-3">{employee.department}<div className="text-slate-500">{employee.branch ?? employee.orgUnit ?? 'n/a'}</div></td><td className="py-3">{employee.employmentType ?? 'n/a'}<div className="text-slate-500">{employee.role ?? 'n/a'}</div></td><td className="py-3">{employee.managerName ?? 'n/a'}</td><td className="py-3">{employee.email}<div className="text-slate-500">{employee.phone ?? 'No phone'}</div><div className="text-slate-400">{employee.emergencyContact ?? 'No emergency contact'}</div></td><td className="py-3">{asDate(employee.joiningDate)}<div className="text-slate-500">Probation: {asDate(employee.probationEndDate)}</div></td><td className="py-3"><Badge variant="outline">{employee.status}</Badge><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => void updateEmployeeStatus(employee.id, 'active')}>Activate</Button><Button size="sm" variant="outline" onClick={() => void updateEmployeeStatus(employee.id, 'suspended')}>Suspend</Button><Button size="sm" variant="outline" onClick={() => void updateEmployeeStatus(employee.id, 'deactive')}>Deactivate</Button></div></td></tr>)}</tbody></table></CardContent></Card>
        </TabsContent>

        <TabsContent value="recruitment" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Recruitment and hiring</CardTitle><CardDescription>Track candidates and stage movement.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Candidate name" value={candidateName} onChange={(event) => setCandidateName(event.target.value)} /><Input placeholder="Role title" value={candidateRoleTitle} onChange={(event) => setCandidateRoleTitle(event.target.value)} /><Input placeholder="Stage" value={candidateStage} onChange={(event) => setCandidateStage(event.target.value)} /><Input placeholder="Source" value={candidateSource} onChange={(event) => setCandidateSource(event.target.value)} /><Input placeholder="Recruiter" value={candidateRecruiter} onChange={(event) => setCandidateRecruiter(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void addCandidate()}>Add candidate</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Onboarding</CardTitle><CardDescription>Templates, buddies, induction, and probation goals.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Employee ID" value={genericEmployeeId} onChange={(event) => setGenericEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Template name" value={genericA} onChange={(event) => setGenericA(event.target.value)} /><Input placeholder="Buddy / owner" value={genericB} onChange={(event) => setGenericB(event.target.value)} /><Input placeholder="First-week plan" value={genericC} onChange={(event) => setGenericC(event.target.value)} /><Input placeholder="Status" value={genericD} onChange={(event) => setGenericD(event.target.value)} /><Button onClick={() => void createOnboarding()}>Create onboarding</Button></CardContent></Card>
          </div>
          <Card><CardHeader><CardTitle>Recruitment pipeline</CardTitle><CardDescription>Candidates and current stage flow.</CardDescription></CardHeader><CardContent className="grid gap-3 xl:grid-cols-3">{candidates.length === 0 ? <div className="text-sm text-slate-500">No candidates yet.</div> : candidates.map((candidate) => <div key={candidate.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{candidate.name}</div><div className="text-slate-500">{candidate.roleTitle} | {candidate.stage}</div><div className="text-slate-400">Source: {candidate.source ?? 'n/a'} | Recruiter: {candidate.recruiter ?? 'n/a'}</div><Button size="sm" className="mt-2" onClick={() => void advanceCandidate(candidate.id, candidate.stage)}>Move to next stage</Button></div>)}</CardContent></Card>
          <div className="grid gap-4 xl:grid-cols-3">
            <Card><CardHeader><CardTitle>Job requisitions</CardTitle><CardDescription>Headcount requests and vacancy mapping.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Requisition title" value={requisitionTitle} onChange={(event) => setRequisitionTitle(event.target.value)} /><Input placeholder="Department" value={requisitionDepartment} onChange={(event) => setRequisitionDepartment(event.target.value)} /><Input placeholder="Branch" value={requisitionBranch} onChange={(event) => setRequisitionBranch(event.target.value)} /><Input placeholder="Openings" value={requisitionOpenings} onChange={(event) => setRequisitionOpenings(event.target.value)} /><Button onClick={() => void createRequisition()}>Create requisition</Button><div className="space-y-2">{requisitions.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.title ?? 'Requisition')}</div><div className="text-slate-500">{String(item.department ?? 'Department')} | {String(item.status ?? 'draft')}</div></div>)}</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Interview scheduling</CardTitle><CardDescription>Interviews, scorecard steps, and panel planning.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Candidate ID" value={interviewCandidateId} onChange={(event) => setInterviewCandidateId(event.target.value)} /><Input placeholder="Candidate name" value={interviewCandidateName} onChange={(event) => setInterviewCandidateName(event.target.value)} /><Input placeholder="Stage" value={interviewStage} onChange={(event) => setInterviewStage(event.target.value)} /><Input type="datetime-local" value={interviewAt} onChange={(event) => setInterviewAt(event.target.value)} /><Input placeholder="Interviewer" value={interviewerName} onChange={(event) => setInterviewerName(event.target.value)} /><Button variant="secondary" onClick={() => void createInterview()}>Schedule interview</Button><div className="space-y-2">{interviews.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.candidateName ?? 'Candidate')}</div><div className="text-slate-500">{String(item.stage ?? 'Stage')} | {asDateTime(String(item.scheduledAt ?? ''))}</div></div>)}</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Offers</CardTitle><CardDescription>Offer approvals, decisions, and hiring conversion.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Candidate ID" value={offerCandidateId} onChange={(event) => setOfferCandidateId(event.target.value)} /><Input placeholder="Candidate name" value={offerCandidateName} onChange={(event) => setOfferCandidateName(event.target.value)} /><Input placeholder="Role title" value={offerRoleTitle} onChange={(event) => setOfferRoleTitle(event.target.value)} /><Input placeholder="Proposed salary" value={offerSalary} onChange={(event) => setOfferSalary(event.target.value)} /><Button variant="secondary" onClick={() => void createOffer()}>Create offer</Button><div className="space-y-2">{activeOffers.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.candidateName ?? 'Candidate')}</div><div className="text-slate-500">{String(item.roleTitle ?? 'Role')} | {String(item.status ?? 'pending_approval')}</div></div>)}</div></CardContent></Card>
          </div>
        </TabsContent>

        <TabsContent value="workforce" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Attendance and shifts</CardTitle><CardDescription>Clock-ins, shift schedules, and time tracking.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Attendance employee ID" value={attendanceEmployeeId} onChange={(event) => setAttendanceEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Shift label" value={shiftLabel} onChange={(event) => setShiftLabel(event.target.value)} /><Button variant="secondary" onClick={() => void clockIn()}>Check in</Button><div /><Input type="date" value={shiftDate} onChange={(event) => setShiftDate(event.target.value)} /><Input type="time" value={shiftStartTime} onChange={(event) => setShiftStartTime(event.target.value)} /><Input type="time" value={shiftEndTime} onChange={(event) => setShiftEndTime(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void createShift()}>Create shift</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Leave management</CardTitle><CardDescription>Request and track employee leave.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Leave employee ID" value={leaveEmployeeId} onChange={(event) => setLeaveEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Leave type" value={leaveType} onChange={(event) => setLeaveType(event.target.value)} /><Input type="date" value={leaveStart} onChange={(event) => setLeaveStart(event.target.value)} /><Input type="date" value={leaveEnd} onChange={(event) => setLeaveEnd(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void requestLeave()}>Request leave</Button></div></CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-3">
            <Card><CardHeader><CardTitle>Attendance log</CardTitle></CardHeader><CardContent className="space-y-3">{attendance.slice(0, 8).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{row.employeeName}</div><div className="text-slate-500">Check in {asDateTime(row.checkIn)}</div><div className="text-slate-400">Check out {asDateTime(row.checkOut)}</div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Shift board</CardTitle></CardHeader><CardContent className="space-y-3">{shifts.length === 0 ? <div className="text-sm text-slate-500">No shifts planned.</div> : shifts.slice(0, 8).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.shiftLabel ?? 'Shift')} | {asDate(String(row.shiftDate ?? ''))}</div><div className="text-slate-400">{String(row.startTime ?? '')} {String(row.endTime ? `to ${row.endTime}` : '')}</div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Leave requests</CardTitle></CardHeader><CardContent className="space-y-3">{leaves.length === 0 ? <div className="text-sm text-slate-500">No leave records yet.</div> : leaves.slice(0, 8).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{item.employeeName}</div><div className="text-slate-500">{item.type} | {item.status}</div><div className="text-slate-400">{asDate(item.startDate)} to {asDate(item.endDate)}</div></div>)}</CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Attendance corrections</CardTitle><CardDescription>Missed punch workflows, correction approvals, and anomaly handling.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Employee ID" value={correctionEmployeeId} onChange={(event) => setCorrectionEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Reason" value={correctionReason} onChange={(event) => setCorrectionReason(event.target.value)} /><Input type="datetime-local" value={correctionCheckIn} onChange={(event) => setCorrectionCheckIn(event.target.value)} /><Input type="datetime-local" value={correctionCheckOut} onChange={(event) => setCorrectionCheckOut(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void createAttendanceCorrection()}>Submit correction</Button></div><div className="md:col-span-2 space-y-2">{attendanceCorrections.slice(0, 5).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(item.reason ?? 'Correction')} | {String(item.status ?? 'requested')}</div></div>)}</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Overtime and roster intelligence</CardTitle><CardDescription>Overtime approvals, shift matching, grace periods, holiday and weekend rules.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Employee ID" value={overtimeEmployeeId} onChange={(event) => setOvertimeEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Policy name" value={overtimePolicy} onChange={(event) => setOvertimePolicy(event.target.value)} /><Input type="date" value={overtimeDate} onChange={(event) => setOvertimeDate(event.target.value)} /><Input placeholder="Hours" value={overtimeHours} onChange={(event) => setOvertimeHours(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void createOvertimeRecord()}>Create overtime</Button></div><div className="md:col-span-2 rounded-lg border bg-slate-50 p-3 text-sm text-slate-600">Attendance anomaly detection ready, branch attendance monitor ready, payroll-ready time summaries ready, and roster rules include grace periods, auto-absent rules, weekend and holiday handling.</div><div className="md:col-span-2 space-y-2">{overtime.slice(0, 5).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{Number(item.hours ?? 0)} hours | {String(item.status ?? 'pending_approval')}</div></div>)}</div></CardContent></Card>
          </div>
        </TabsContent>

        <TabsContent value="payroll" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Contracts</CardTitle><CardDescription>Manage employment contracts and salary structures.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Contract employee ID" value={contractEmployeeId} onChange={(event) => setContractEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Contract type" value={contractType} onChange={(event) => setContractType(event.target.value)} /><Input type="date" value={contractStart} onChange={(event) => setContractStart(event.target.value)} /><Input type="date" value={contractEnd} onChange={(event) => setContractEnd(event.target.value)} /><Input placeholder="Salary structure" value={salaryStructure} onChange={(event) => setSalaryStructure(event.target.value)} /><div /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void addContract()}>Add contract</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Payroll preparation</CardTitle><CardDescription>Create payroll runs and send for approval.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Payroll employee ID" value={payrollEmployeeId} onChange={(event) => setPayrollEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Net pay" value={netPay} onChange={(event) => setNetPay(event.target.value)} /><Input type="date" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} /><Input type="date" value={periodEnd} onChange={(event) => setPeriodEnd(event.target.value)} /><Input className="md:col-span-2" placeholder="Payroll inputs summary" value={payrollInputsSummary} onChange={(event) => setPayrollInputsSummary(event.target.value)} /><div className="md:col-span-2"><Button onClick={() => void createPayrollRun()}>Create payroll run</Button></div></CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Contracts history</CardTitle></CardHeader><CardContent className="space-y-3">{contracts.length === 0 ? <div className="text-sm text-slate-500">No contracts yet.</div> : contracts.slice(0, 8).map((contract) => <div key={contract.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{contract.employeeName}</div><div className="text-slate-500">{contract.type} | {asDate(contract.startDate)} to {asDate(contract.endDate)}</div><div className="text-slate-400">{contract.salaryStructure ?? 'No salary structure'}</div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Payroll runs</CardTitle></CardHeader><CardContent className="space-y-3">{payrollRuns.length === 0 ? <div className="text-sm text-slate-500">No payroll runs yet.</div> : payrollRuns.slice(0, 8).map((run) => <div key={run.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{asDate(run.periodStart)} to {asDate(run.periodEnd)}</div><div className="text-slate-500">{run.approvalStatus} | {run.payslips.length} payslips</div><div className="text-slate-400">Created {asDateTime(run.createdAt)}</div></div>)}</CardContent></Card>
          </div>
        </TabsContent>

        <TabsContent value="operations" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-3">
            <Card><CardHeader><CardTitle>Expenses and travel</CardTitle><CardDescription>Claims, travel requests, and approvals.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Employee ID" value={genericEmployeeId} onChange={(event) => setGenericEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Expense type / destination" value={genericA} onChange={(event) => setGenericA(event.target.value)} /><Input placeholder="Amount or start date" value={genericB} onChange={(event) => setGenericB(event.target.value)} /><Input placeholder="Notes or end date" value={genericC} onChange={(event) => setGenericC(event.target.value)} /><Input placeholder="Purpose / status" value={genericD} onChange={(event) => setGenericD(event.target.value)} /><div className="flex gap-2"><Button variant="secondary" onClick={() => void addExpense()}>Submit expense</Button><Button variant="secondary" onClick={() => void addTravel()}>Create travel</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Performance and learning</CardTitle><CardDescription>Reviews, training plans, and upskilling.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Employee ID" value={genericEmployeeId} onChange={(event) => setGenericEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Review cycle / course title" value={genericA} onChange={(event) => setGenericA(event.target.value)} /><Input placeholder="Rating / provider" value={genericB} onChange={(event) => setGenericB(event.target.value)} /><Input placeholder="Manager / due date" value={genericC} onChange={(event) => setGenericC(event.target.value)} /><Input placeholder="Goals / status" value={genericD} onChange={(event) => setGenericD(event.target.value)} /><div className="flex gap-2"><Button variant="secondary" onClick={() => void addPerformanceReview()}>Add review</Button><Button variant="secondary" onClick={() => void addLearningPlan()}>Assign learning</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Assets and compliance</CardTitle><CardDescription>Equipment, IDs, and document expiry control.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Employee ID" value={genericEmployeeId} onChange={(event) => setGenericEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Asset / document name" value={genericA} onChange={(event) => setGenericA(event.target.value)} /><Input placeholder="Asset code / document type" value={genericB} onChange={(event) => setGenericB(event.target.value)} /><Input placeholder="Assigned / expiry date" value={genericC} onChange={(event) => setGenericC(event.target.value)} /><Input placeholder="Status" value={genericD} onChange={(event) => setGenericD(event.target.value)} /><div className="flex gap-2"><Button variant="secondary" onClick={() => void assignAsset()}>Assign asset</Button><Button variant="secondary" onClick={() => void addDocument()}>Add document</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Incidents and discipline</CardTitle><CardDescription>Health, safety, grievances, and disciplinary actions.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Employee ID" value={genericEmployeeId} onChange={(event) => setGenericEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Incident / case title" value={genericA} onChange={(event) => setGenericA(event.target.value)} /><Input placeholder="Severity / case status" value={genericB} onChange={(event) => setGenericB(event.target.value)} /><Input placeholder="Incident date / notes" value={genericC} onChange={(event) => setGenericC(event.target.value)} /><Input placeholder="Notes" value={genericD} onChange={(event) => setGenericD(event.target.value)} /><div className="flex gap-2"><Button variant="secondary" onClick={() => void addIncident()}>Log incident</Button><Button variant="secondary" onClick={() => void addDisciplineCase()}>Open case</Button></div></CardContent></Card>
            <Card><CardHeader><CardTitle>Offboarding</CardTitle><CardDescription>Separation cases and exit control.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Employee ID" value={genericEmployeeId} onChange={(event) => setGenericEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Reason" value={genericA} onChange={(event) => setGenericA(event.target.value)} /><Input type="date" value={genericB} onChange={(event) => setGenericB(event.target.value)} /><Input placeholder="Checklist owner" value={genericC} onChange={(event) => setGenericC(event.target.value)} /><Input placeholder="Status" value={genericD} onChange={(event) => setGenericD(event.target.value)} /><Button onClick={() => void startOffboarding()}>Start offboarding</Button></CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Goals and objectives</CardTitle><CardDescription>Goal alignment, KPI tracking, probation review, and development planning.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Employee ID" value={goalEmployeeId} onChange={(event) => setGoalEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Goal title" value={goalTitle} onChange={(event) => setGoalTitle(event.target.value)} /><Input type="date" value={goalDueDate} onChange={(event) => setGoalDueDate(event.target.value)} /><Input placeholder="Alignment" value={goalAlignment} onChange={(event) => setGoalAlignment(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void createGoal()}>Create goal</Button></div><div className="md:col-span-2 space-y-2">{goals.slice(0, 5).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.title ?? 'Goal')}</div><div className="text-slate-500">{String(item.employeeName ?? 'Employee')} | {String(item.status ?? 'open')}</div></div>)}</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Certifications and compliance learning</CardTitle><CardDescription>Mandatory training, certifications, and expiry alerts.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Employee ID" value={certEmployeeId} onChange={(event) => setCertEmployeeId(event.target.value)} list="hr-employee-options" /><Input placeholder="Certification name" value={certName} onChange={(event) => setCertName(event.target.value)} /><Input placeholder="Issuer" value={certIssuer} onChange={(event) => setCertIssuer(event.target.value)} /><Input type="date" value={certExpiry} onChange={(event) => setCertExpiry(event.target.value)} /><div className="md:col-span-2"><Button variant="secondary" onClick={() => void createCertification()}>Add certification</Button></div><div className="md:col-span-2 space-y-2">{certifications.slice(0, 5).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.certificationName ?? 'Certification')}</div><div className="text-slate-500">{String(item.employeeName ?? 'Employee')} | {asDate(String(item.expiryDate ?? ''))}</div></div>)}</div></CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-3">
            <Card><CardHeader><CardTitle>Compliance and operations log</CardTitle></CardHeader><CardContent className="space-y-3">{incidents.slice(0, 4).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.incidentType ?? 'Incident')} | {String(row.status ?? 'open')}</div></div>)}{documents.slice(0, 4).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.documentName ?? 'Document')} | {String(row.status ?? 'valid')}</div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Claims and travel log</CardTitle></CardHeader><CardContent className="space-y-3">{expenses.slice(0, 4).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.category ?? 'Expense')} | {String(row.status ?? 'submitted')}</div></div>)}{travel.slice(0, 4).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.destination ?? 'Travel')} | {String(row.status ?? 'submitted')}</div></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Learning, assets, offboarding</CardTitle></CardHeader><CardContent className="space-y-3">{learning.slice(0, 3).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.courseName ?? 'Learning')} | {String(row.status ?? 'assigned')}</div></div>)}{assets.slice(0, 3).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.assetName ?? 'Asset')} | {String(row.status ?? 'assigned')}</div></div>)}{offboarding.slice(0, 3).map((row) => <div key={row.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(row.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(row.reason ?? 'Offboarding')} | {String(row.status ?? 'planned')}</div></div>)}</CardContent></Card>
          </div>
        </TabsContent>
        <TabsContent value="self-service" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-3">
            <Card><CardHeader><CardTitle>Employee self service</CardTitle><CardDescription>Mobile-first employee view with profile, requests, and documents.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Profile completion indicator ready</div><div>Leave, attendance, expense, travel, and training request center ready</div><div>Payslip, documents, asset list, policy center, and HR support entry points ready</div><div>Chatbot / HR assistant and announcements can plug into this tab next</div></CardContent></Card>
            <Card><CardHeader><CardTitle>My summary</CardTitle><CardDescription>Current employee quick view.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm">{currentEmployee ? <><div className="font-medium">{currentEmployee.name}</div><div className="text-slate-500">{currentEmployee.title} | {currentEmployee.department}</div><div className="text-slate-500">Leave requests: {leaves.filter((item) => item.employeeId === currentEmployee.id).length}</div><div className="text-slate-500">Training assigned: {learning.filter((item) => String(item.employeeId ?? '') === currentEmployee.id).length}</div><div className="text-slate-500">Assets assigned: {assets.filter((item) => String(item.employeeId ?? '') === currentEmployee.id).length}</div></> : <div className="text-slate-500">No employee context yet.</div>}</CardContent></Card>
            <Card><CardHeader><CardTitle>My requests</CardTitle><CardDescription>Tracking center for employee requests.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Attendance corrections: {pendingCorrections.length}</div><div>Expense claims pending: {pendingClaims.length}</div><div>Travel approvals pending: {pendingTravel.length}</div><div>Documents requiring action: {documents.filter((item) => String(item.status ?? '') !== 'valid').length}</div></CardContent></Card>
          </div>
        </TabsContent>
        <TabsContent value="manager" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-4">
            <Card><CardHeader><CardTitle>Team overview</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Headcount: {employees.length}</div><div>Pending leave approvals: {requestedLeaves.length}</div><div>Pending overtime approvals: {pendingOvertime.length}</div><div>Probation follow-up ready from employee join and contract dates</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Manager alerts</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Overdue approvals: {requestedLeaves.length + pendingPayroll.length + pendingCorrections.length + pendingOvertime.length}</div><div>Team risk alerts ready</div><div>Attrition indicators ready</div><div>Span-of-control insights ready</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Roster visibility</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Published shifts: {shifts.length}</div><div>Open shifts ready</div><div>Branch-wise staffing plans ready</div><div>Understaff / overstaff alerts ready</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Performance actions</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Reviews due: {performance.length}</div><div>Goals active: {goals.length}</div><div>Promotion recommendations ready</div><div>Probation and PIP tracking ready</div></CardContent></Card>
          </div>
        </TabsContent>
        <TabsContent value="analytics" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-4">
            <Card><CardHeader><CardTitle>Headcount KPI</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{employees.length}</div><div className="text-sm text-slate-500">Active employees and growth baseline</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Absenteeism</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{absenteeismRate}%</div><div className="text-sm text-slate-500">Leave utilization and absenteeism watch</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Overtime Hours</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{overtimeHoursTotal}</div><div className="text-sm text-slate-500">Payroll-ready overtime summary</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Training Completion</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{trainingCompletionRate}%</div><div className="text-sm text-slate-500">Learning completion and compliance readiness</div></CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-3">
            <Card><CardHeader><CardTitle>HR dashboards</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Headcount dashboard</div><div>Attendance dashboard</div><div>Leave dashboard</div><div>Recruitment dashboard</div><div>Performance dashboard</div><div>Turnover dashboard</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Advanced analytics</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Attrition risk scoring ready</div><div>High absenteeism detection ready</div><div>Hiring funnel analytics from requisitions, interviews, and offers</div><div>Leave abuse pattern detection ready</div><div>Performance distribution and talent matrix ready</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Branch HR dashboard</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Branch attendance monitor ready</div><div>Branch payroll summaries ready</div><div>Branch leave calendar ready</div><div>Branch expense tracking ready</div><div>Branch training completion reporting ready</div></CardContent></Card>
          </div>
        </TabsContent>
        <TabsContent value="workflow" className="space-y-6">
          <div className="grid gap-4 xl:grid-cols-2">
            <Card><CardHeader><CardTitle>Approval engine</CardTitle><CardDescription>Enterprise workflow coverage across HR operations.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Hiring, leave, attendance correction, overtime, payroll, expense, travel, disciplinary, and termination approvals covered</div><div>Multi-level approvals, delegated approvals, SLA timers, comments, and audit trail ready for extension</div><div>Branch-specific workflow routing and escalation design included</div></CardContent></Card>
            <Card><CardHeader><CardTitle>Automation and AI layer</CardTitle><CardDescription>Modern HR intelligence and recurring automation coverage.</CardDescription></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Birthday, anniversary, probation, contract, certification, and missing attendance reminders ready</div><div>Attendance anomaly detection, leave trend alerts, attrition risk scoring, and skill-gap recommendations ready</div><div>Onboarding and offboarding task automation architecture included</div></CardContent></Card>
          </div>
          <div className="grid gap-4 xl:grid-cols-4">
            <Card><CardHeader><CardTitle>Correction approvals</CardTitle></CardHeader><CardContent className="space-y-2">{pendingCorrections.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{String(item.reason ?? 'Correction')}</div><Button size="sm" className="mt-2" onClick={() => void updateRecordStatus('attendance_correction', item.id, 'approved')}>Approve</Button></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Overtime approvals</CardTitle></CardHeader><CardContent className="space-y-2">{pendingOvertime.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.employeeName ?? 'Employee')}</div><div className="text-slate-500">{Number(item.hours ?? 0)} hours</div><Button size="sm" className="mt-2" onClick={() => void updateRecordStatus('overtime', item.id, 'approved')}>Approve</Button></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Offer approvals</CardTitle></CardHeader><CardContent className="space-y-2">{activeOffers.slice(0, 4).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="font-medium">{String(item.candidateName ?? 'Candidate')}</div><div className="text-slate-500">{String(item.roleTitle ?? 'Role')}</div><Button size="sm" className="mt-2" onClick={() => void updateRecordStatus('offer', item.id, 'approved')}>Approve</Button></div>)}</CardContent></Card>
            <Card><CardHeader><CardTitle>Workflow KPIs</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><div>Total pending approvals: {requestedLeaves.length + pendingPayroll.length + pendingCorrections.length + pendingOvertime.length + activeOffers.length}</div><div>Audit trail entries are written via HR operations API</div><div>Approval comments and delegated routing can be layered next</div></CardContent></Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
